baseURL = "http://sumantabose.me/new-site/"
#relativeURLs = true
title = "Sumanta Bose"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""
publishDir = "docs"

theme = "minimo-loc"

disqusShortname = ""
googleAnalytics = ""

Paginate = 20
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Senior Research Engineer"
title404 = "Site not found. Try later."

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = "Copyright"
holder = "Sumanta Bose"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
taxonomyCloudShuffle = true
# accentColor = "#ffcd00"
accentColor = "#a8a8a8"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu","social_menu"]#,"taxonomy_cloud","social_menu"]
footer = ["powered_by"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
# codepen = "MunifTanjim"
email = "sumantabose@gmail.com"
facebook = "sumantab"
github = "sumantabose"
# gitlab = "MunifTanjim"
instagram = "sumobose"
linkedin = "sumanta-bose-1a792a36"
twitter = "sumobose"
# telegram = "MunifTanjim"
google_scholar = "7ISycOUAAAAJ"
# youtube = "UCT-U0rNerYxItGcuoPX-WYA"

[params.comments]
enable = false

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = "MunifTanjim"
repository = "minimo"
branch = "master"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
post = "/:year/:month/:title/"
page = "/:slug/"

# [[menu.main]]
# name = "Repo"
# weight = -10
# identifier = "repository"
# url = "https://github.com/sumantabose"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
#[languages.es]
#lang = "es"
#languageName = "Spanish"
#weight = 1
